services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgres://postgres:rUdGERaNTior@localhost:5432/postgres
      NEXTAUTH_URL: http://localhost:3000
    depends_on:
      - app-db
    networks:
      - app-network

  app-db:
    image: postgres:15
    container_name: app-db
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rUdGERaNTior
    volumes:
      - app-db-data:/var/lib/postgresql/data
    networks:
      - app-network

  app-nginx:
    image: nginx:alpine
    container_name: app-nginx
    restart: unless-stopped
    ports:
      - '80:80'
    volumes:
      - ./nginx/nextjs.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - app-network

  keycloak-db:
    image: postgres:15
    container_name: keycloak-db
    restart: unless-stopped
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rBeNTaFNITiN
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
    networks:
      - app-network

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: keycloak
    restart: unless-stopped
    command: start-dev
    ports:
      - '8080:8080'
    # volumes:
    #   - ./keycloak/swift-loans-theme:/opt/keycloak/themes/swift-loans
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_DATABASE: postgres
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: rBeNTaFNITiN
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    depends_on:
      - keycloak-db
    networks:
      - app-network

  keycloak-nginx:
    image: nginx:alpine
    container_name: keycloak-nginx
    restart: unless-stopped
    ports:
      - '81:80'
    volumes:
      - ./nginx/keycloak.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - keycloak
    networks:
      - app-network

volumes:
  app-db-data:
  keycloak-db-data:

networks:
  app-network:
